### ISSUE TITLE
What is boost?

### ISSUE THREAD

**Issue by hrstoyanov** [OpenLiberty/boost#279]
Hi,
How is Boost set of plug-ins different from the old OL Gradle/MAven plugins? Any documentation pointers?

I am also a bit puzzled as to why was Groovy used again for the Gradle plug-in? Gradle does not like Groovy anymore. It likes Kotlin! But it is always safest/best to just write Gradle plugins in .. Java! Writing the plug-in in Java will attract the wides audience of contributors!

**Comment by cherylking** [comment]
Thank you for your observation regarding our use of Groovy in the Gradle plugins. We will certainly take that into consideration going forward.

As for what are the Boost plug-ins and how they differ from the existing OL Gradle/Maven plug-ins, we are still in the design phase. Our intention for these plug-ins is to provide a more generic application centric manner for configuration, minimizing the need to know Liberty specific configuration. We want to simplify dependency management and deployment configuration so that the developer can focus on developing their application.

I'll make sure the README gets updated accordingly. Thank you for your interest!

**Comment by hrstoyanov** [comment]
@cherylking Thanks for the clarification, fell free to close this issue.
